User.create(user_name: 'kevin', password: 'password', points: 10000)
User.create(user_name: 'luis', password: 'password', points: 9000)
User.create(user_name: 'shawn', password: 'password', points: 99999)
User.create(user_name: 'justin', password: 'password', points: 3123)
User.create(user_name: 'scott', password: 'password', points: 1222)
User.create(user_name: 'vidhi', password: 'password', points: 4000)
User.create(user_name: 'bob', password: 'password', points: 92921)
User.create(user_name: 'tom', password: 'password', points: 40302)
User.create(user_name: 'jerry', password: 'password', points: 20320)
User.create(user_name: 'daniel', password: 'password', points: 32821)
User.create(user_name: 'will', password: 'password', points: 4433)


Machine.create(name: 'Tony')
Machine.create(name: 'Josh')
