User.create(user_name: 'kevin', password: 'password', points: 5000)
User.create(user_name: 'luis', password: 'password', points: 9000)
User.create(user_name: 'shawn', password: 'password', points: 120323)
User.create(user_name: 'justin', password: 'password', points: 31223)
User.create(user_name: 'scott', password: 'password', points: 72222)
User.create(user_name: 'vidhi', password: 'password', points: 40200)
User.create(user_name: 'robert', password: 'password', points: 92921)
User.create(user_name: 'tom', password: 'password', points: 40302)
User.create(user_name: 'nathan', password: 'password', points: 50320)
User.create(user_name: 'minh', password: 'password', points: 32821)
User.create(user_name: 'sam', password: 'password', points: 44333)
User.create(user_name: 'chris', password: 'password', points: 66213)
User.create(user_name: 'nick', password: 'password', points: 54333)
User.create(user_name: 'charles', password: 'password', points: 72133)
User.create(user_name: 'pratikshya', password: 'password', points: 21032)
User.create(user_name: 'ryan', password: 'password', points: 34339)

Dice.create(name: 'Dice')
RPS.create(name: 'Rock Paper Scissors')
SlotMachine.create(name: 'Slot Machine')
BattleShip.create(name: 'Battleship')


Machine.create(name: 'Tony', game_id: 1)
Machine.create(name: 'Josh', game_id: 2)
Machine.create(name: 'Kay', game_id: 3)
Machine.create(name: 'Trump', game_id: 4)
